name: Maven Package

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -B -ntp -DskipTests=true -f pom.xml

    - name: Prepare artifact
      run: |
        cp ./target/viro-1.0.jar ./bin/viro.jar

    - name: Upload java release
      uses: actions/upload-artifact@v2
      with:
        name: viro
        path: ./bin/viro.jar